---
name: zoekt_exact_search
feature_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/434417
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/140346
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/436457
milestone: '16.8'
group: group::global search
type: gitlab_com_derisk
default_enabled: false
