---
name: admin_vulnerability
description: Allows admin access to the vulnerability reports.
introduced_by_issue: https://gitlab.com/gitlab-org/gitlab/-/issues/412536
introduced_by_mr: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/121534
feature_category: vulnerability_management
milestone: '16.1'
group_ability: true
project_ability: true
requirements:
  - read_vulnerability
available_from_access_level: 40
