---
description: Pipeline created with secrets (Azure Key Vault integration) defined
category: InternalEventTracking
action: create_secrets_azure_key_vault
identifiers:
- namespace
- user
product_section: ci
product_stage: verify
product_group: pipeline_security
milestone: '16.9'
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/143768
distributions:
- ee
tiers:
- premium
- ultimate
