---
description: Triggered when a user opts to filter out anonymous users on an analytics dashboard.
category: InternalEventTracking
action: exclude_anonymised_users
label_description:
property_description:
value_description:
extra_properties:
identifiers:
- project
- user
- namespace
product_section: analytics
product_stage: monitor
product_group: product_analytics
milestone: "16.7"
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/138150
distributions:
- ee
tiers:
- ultimate
