---
description: Export runner usage as CSV
category: InternalEventTracking
action: export_runner_usage_by_project_as_csv
identifiers:
- user
product_section: ci
product_stage: verify
product_group: runner
milestone: '16.9'
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/142328
distributions:
- ee
tiers:
- ultimate
