---
description: User created a new issue from an epic
category: InternalEventTracking
internal_events: true
action: g_project_management_users_epic_issue_added_from_epic
label_description:
property_description:
value_description:
extra_properties:
identifiers:
- project
- user
- namespace
product_section: dev
product_stage: plan
product_group: product_planning
milestone: "16.4"
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/131495
distributions:
- ee
tiers:
- premium
