---
description: Counts Licenses List page views
category: InternalEventTracking
action: licenses_list_viewed
identifiers:
- project
- namespace
- user
product_section: sec
product_stage: secure
product_group: composition_analysis
milestone: '16.10'
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/145721
distributions:
- ee
tiers:
- ultimate
