---
description: Triggered when a user views the visualization designer.
internal_events: true
action: user_viewed_visualization_designer
label_description:
property_description:
value_description:
extra_properties:
identifiers:
- project
- user
- namespace
product_section: analyze
product_stage: analytics
product_group: product_analytics
milestone: "16.6"
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/135708
distributions:
- ee
tiers:
- ultimate
