---
description: User edited analytics cluster configuration
category: InternalEventTracking
action: user_edited_cluster_configuration
label_description:
property_description:
value_description:
extra_properties:
identifiers:
- project
- user
- namespace
product_section: analytics
product_stage: analytics
product_group: product_analytics
milestone: "16.4"
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/131168
distributions:
- ee
tiers:
- ultimate
