---
description: Visit to /groups/:group/-/analytics/productivity_analytics
category: InternalEventTracking
action: view_productivity_analytics
identifiers:
- namespace
- user
product_section: dev
product_stage: manage
product_group: optimize
milestone: '17.0'
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/149959
distributions:
- ee
tiers:
- premium
- ultimate
