---
name: geo_proxy_check_pipeline_refs
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/137732
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/434041
milestone: '16.7'
type: development
group: group::geo
default_enabled: false
