---
name: pending_status_check_responses
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/124811
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/425951
milestone: '16.5'
type: development
group: group::compliance
default_enabled: true
