---
name: security_policies_unenforceable_rules_notification
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/133627
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/427746
milestone: '16.7'
type: development
group: group::security policies
default_enabled: false
