---
name: standalone_finding_modal_merge_request_widget
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/issues/413516
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/425936
milestone: '16.5'
type: development
group: group::threat insights
default_enabled: true
