---
name: timeout_status_check_responses
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/133383
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/427356
milestone: '16.6'
type: development
group: group::compliance
default_enabled: false
