---
data_category: optional
key_path: redis_hll_counters.epics_usage.g_project_management_users_awarding_epic_emoji_monthly
description: Counts of MAU awarding emoji on epic
product_section: dev
product_stage: plan
product_group: product_planning
value_type: number
status: active
milestone: '13.12'
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/60787
time_frame: 28d
data_source: internal_events
options:
  events:
    - g_project_management_users_awarding_epic_emoji
events:
  - name: g_project_management_users_awarding_epic_emoji
    unique: user.id
distribution:
- ee
tier:
- premium
- ultimate
performance_indicator_type: []
