---
name: group_saved_replies_flag
feature_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/330098
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/143660
rollout_issue_url:
milestone: '16.9'
group: group::code review
type: wip
default_enabled: false
