---
data_category: optional
key_path: counts.status_page_incident_publishes
description: Cumulative count of usages of publish operation
product_section: ops
product_stage: monitor
product_group: respond
value_type: number
status: active
time_frame: all
data_source: internal_events
events:
  - name: status_page_incident_published
distribution:
  - ee
tier:
  - ultimate
performance_indicator_type: []
milestone: '<13.9'
